import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextProvider } from "./NextUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Summare.ai - AI article summaries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
